name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - master
  
  push:
    branches:
      - main
      - master
      - develop
  
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.22.2'

      - run: flutter config --no-analytics
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
        
      